---
functional:
  - Пользователь должен иметь возможность регистрироваться на сайте
  - Пользователь должен иметь возможность авторизовываться на сайте
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность выбирать язык программирования
  - Пользователь должен иметь возможность писать код в редакторе
  - Пользователь должен иметь возможность видеть два редактора: слева - свой редактор, справа - соперника
  - Каждый пользователь должен видеть код своего соперника в режиме он-лайн
  - Пользователь должен иметь кнопку "Run" для проверки своего решения
  - Попыток проверки должно быть неограниченно
  - Игра может длиться 60 минут
  - Когда один из игроков находит верное решение, обоим игрокам должно
    высвечивается модальное окно, где написано, кто является победителем этой
    игры
  - Победитель-игрок должен иметь возможность выйти из игры по нажатию кнопки
    "exit"
  - Соперник должен иметь возможность выйти из игры по нажатию кнопки "exit"
  - Когда оба игрока вышли, игра должна считается полностью законченной и
    удаляется из памяти
  - Пользователь должен иметь возможность просматривать свою статистику игр
  - Пользователь должен иметь возможность просматривать свой рейтинг
  - Пользователь должен иметь возможность просматривать общий рейтинг всех
    игроков
  - Пользователь должен иметь возможность просматривать историю игр
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей)
implicit:
  - Сайт должен иметь версию для слабовидящих
  - Пользователь должен иметь возможность связаться с поддержкой

